name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{secrets.DH_USER}} -p ${{secrets.DH_PASS}}
    
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{secrets.DH_USER}}/${{secrets.DH_REPO}}:${{github.sha}}
    
    - name: Push Docker Image
      run: docker push ${{secrets.DH_USER}}/${{secrets.DH_REPO}}:${{github.sha}}
